---
- name: run docker container
  hosts: all
  become: true

  tasks:

  - name: install pip
    apt:
      name: python3-pip
      state: latest

  - name: Install Docker Module for Python
    pip:
      name: docker-py

  - name: start docker
    docker_container:
      name: reddit
      image: rasdark/otus-reddit:1.0
      ports:
        - "9292:9292"
      state: started
      restart: true
